spring.application.name=AcousticWeb Backend

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.thjptxnhxsdxoqfeitzu
spring.datasource.password=7Zr474SX40'*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.cors.allowed-origin=${FRONTEND_URL:http://localhost:5173}

spring.security.user.name=admin
spring.security.user.password=1234